In [1]:
import numpy as np
n = 6
m = 2

In [3]:
##Problem 1
arr = np.zeros((n,n))
arr[::2,::2] = 1
arr[1::2,1::2] = 1
print arr

[[ 1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.]]


In [6]:
##Problem 2
arr = np.random.rand(n,n)
arr = arr[np.argsort(arr[:,m-1])]

In [8]:
##Problem 3
arr = np.tile(np.arange(n),(n,1))
arr = arr + arr.T
print arr

[[ 0  1  2  3  4  5]
 [ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]]
